spring:
  application:
    name: my-cloud-eureka
server:
  port: 8012
eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: true #表示是否将自己注册到Eureka Server，默认为true
    fetch-registry: true #表示是否从Eureka Server获取注册信息，默认为true
    service-url:
      defaultZone: http://localhost:8011/eureka/
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。 默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔