spring:
  application:
    name: my-cloud-cunsumer
server:
  port: 8041
eureka:
  instance:
    hostname: cunsumer
  client:
    service-url:
      defaultZone: http://eureka1:8012/eureka/ #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔